# -*- coding: utf-8 -*-
"""ClinicaRanika.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8zaMUSrBmqp-p34DOcR3a3-A4SwqAwN
"""

!pip install paho-mqtt==1.6.1

import paho.mqtt.client as mqtt
import json
import random
import time

BROKER_MQTT = "54.227.95.166"
PORTA = 1883
TOPICO = "saude/dados"

def gerar_sinais_vitais():
    # Gera batimentos entre 60 e 100 bpm (normal) com chance de pico
    bpm = random.randint(60, 100)
    if random.random() > 0.9: # 10% de chance de uma anomalia (taquicardia)
        bpm = random.randint(110, 140)

    # Gera temperatura entre 36.0 e 37.5 (normal) com chance de febre
    temperatura = round(random.uniform(36.0, 37.5), 1)
    if random.random() > 0.8: # 20% de chance de febre
        temperatura = round(random.uniform(37.8, 39.5), 1)

    return {
        "paciente_id": "LEITO-01",
        "bpm": bpm,
        "temperatura": temperatura
    }

# Configura a conexão MQTT
cliente = mqtt.Client()

print(f"Conectando ao servidor AWS no IP {BROKER_MQTT}...")
cliente.connect(BROKER_MQTT, PORTA)
print("Conectado com sucesso! Iniciando monitoramento...\n")

# Loop infinito enviando dados a cada 5 segundos
try:
    while True:
        dados = gerar_sinais_vitais()
        mensagem_json = json.dumps(dados)

        cliente.publish(TOPICO, mensagem_json)
        print(f" Sinais enviados: {mensagem_json}")

        time.sleep(5) # Aguarda 5 segundos até a próxima leitura
except KeyboardInterrupt:
    print("\nMonitoramento encerrado.")
    cliente.disconnect()